In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [53]:
df = pd.read_csv('D:\\AI-DataScience-Portfolio\\student-mat.csv')

In [54]:
df = pd.read_csv("D:\\AI-DataScience-Portfolio\\student-mat.csv", sep=";")

In [55]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [56]:
# 2. Create a shallow copy
df_shallow = df.copy(deep=False)

In [57]:
df_deep = df.copy(deep=True)

In [58]:
df_deep.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [59]:
df_deep.index

RangeIndex(start=0, stop=395, step=1)

In [60]:
df_deep.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='str')

In [61]:
df_deep.size

13035

In [62]:
df_deep.shape

(395, 33)

In [63]:
df_deep.memory_usage(deep=True)

Index           132
school        20145
sex           19750
age            3160
address       19750
famsize       20540
Pstatus       19750
Medu           3160
Fedu           3160
Mjob          21907
Fjob          21779
reason        21891
guardian      21693
traveltime     3160
studytime      3160
failures       3160
schoolsup     20196
famsup        20387
paid          20326
activities    20346
nursery       20459
higher        20520
internet      20474
romantic      20277
famrel         3160
freetime       3160
goout          3160
Dalc           3160
Walc           3160
health         3160
absences       3160
G1             3160
G2             3160
G3             3160
dtype: int64

In [64]:
df_deep.ndim

2

In [65]:
df_deep.head(3)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10

In [66]:
# in this thisfuncation  show the df_deep.at[row ,column_name]
df_deep.at[0, "school"]

'GP'

In [67]:
#when you shoure about the index of row and column then use this funcation otherwise use df_deep.at[row,column_name]  it will be not include the index column
df.iat[0,4]

'GT3'

In [68]:
df_deep.loc[0,'age']

np.int64(18)

In [69]:
#by using this ( : ) it will be show the all rows in a perticular column 
df_deep.loc[:,"age"]

0      18
1      17
2      15
3      15
4      16
       ..
390    20
391    17
392    21
393    18
394    19
Name: age, Length: 395, dtype: int64