In [79]:
import numpy as np
import pandas as pd

In [80]:
dict1 = {
    "name": ["harry","rohan","skillf","shubh","mohan"],
    "marks":[92 ,34 ,24 ,37, 85],
    "city":["delhi","mumbai","chennai","bangalore","hyderabad"]                  }

In [81]:
df_rel = pd.DataFrame(dict1)

In [82]:
df_rel

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [83]:
df_rel.to_csv("small_pandas_data.csv")

In [84]:
df_rel.to_csv("small_pandas_data_without_index.csv", index=False)

In [85]:
df_rel

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [86]:
df_rel.head(2)

    name  marks    city
0  harry     92   delhi
1  rohan     34  mumbai

In [87]:
df_rel.tail(2)

    name  marks       city
3  shubh     37  bangalore
4  mohan     85  hyderabad

In [88]:
df_rel.describe()

           marks
count   5.000000
mean   54.400000
std    31.595886
min    24.000000
25%    34.000000
50%    37.000000
75%    85.000000
max    92.000000

In [89]:
df_rel.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   marks   5 non-null      int64
 2   city    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [90]:
df_rel["city"]

0        delhi
1       mumbai
2      chennai
3    bangalore
4    hyderabad
Name: city, dtype: str

In [91]:
df_rel[["name","city"]]

     name       city
0   harry      delhi
1   rohan     mumbai
2  skillf    chennai
3   shubh  bangalore
4   mohan  hyderabad

In [92]:
df_rel.loc[0]

name     harry
marks       92
city     delhi
Name: 0, dtype: object

In [93]:
df =df_rel.copy(deep =True)

In [94]:
df["name"][0] ="sonu"

C:\Users\JON\AppData\Local\Temp\ipykernel_9124\3738989102.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["name"][0] ="sonu"

In [95]:
df.index = ["first","second","third","fourth","fifth"]

In [96]:
pd.Series([1,2,3,4,5], index=["a","b","c","d","e"])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [97]:
pd.DataFrame(dict1)

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [98]:
newdf = pd.DataFrame(np.random.rand(350,4),index =np.arange(350),columns =["A","B","C","D"])

In [99]:
newdf

            A         B         C         D
0    0.092623  0.176107  0.552909  0.529047
1    0.481562  0.138628  0.195329  0.202858
2    0.441254  0.158609  0.135590  0.377911
3    0.790770  0.886546  0.867009  0.525938
4    0.766735  0.378818  0.173932  0.847591
..        ...       ...       ...       ...
345  0.996070  0.011388  0.666542  0.995532
346  0.907824  0.729131  0.470079  0.108233
347  0.195336  0.714755  0.968391  0.762745
348  0.823318  0.031568  0.405718  0.317209
349  0.876429  0.237590  0.148617  0.257928

[350 rows x 4 columns]

In [100]:
newdf = pd.DataFrame(np.random.rand(350,4),index =np.arange(350),columns =["A","B","C","D"]).head()
newdf

          A         B         C         D
0  0.989929  0.315154  0.947237  0.700563
1  0.259696  0.295587  0.584811  0.086982
2  0.528236  0.090092  0.105535  0.957328
3  0.049764  0.654670  0.486447  0.819298
4  0.351391  0.308894  0.046174  0.821674

In [101]:
newdf = pd.DataFrame(np.random.rand(50,4),index =np.arange(50),columns =["A","B","C","D"]).tail()
newdf.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.424746  0.525758  0.504154  0.748928
std    0.264838  0.353186  0.138632  0.228502
min    0.066038  0.178293  0.363312  0.399153
25%    0.242702  0.201734  0.393205  0.671497
50%    0.544619  0.471826  0.465014  0.787821
75%    0.546284  0.828424  0.628677  0.900605
max    0.724085  0.948514  0.670562  0.985563

In [102]:
newdf.tail()

           A         B         C         D
45  0.066038  0.471826  0.393205  0.671497
46  0.242702  0.948514  0.363312  0.399153
47  0.546284  0.201734  0.628677  0.787821
48  0.544619  0.828424  0.465014  0.985563
49  0.724085  0.178293  0.670562  0.900605

In [103]:
newdf.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.424746  0.525758  0.504154  0.748928
std    0.264838  0.353186  0.138632  0.228502
min    0.066038  0.178293  0.363312  0.399153
25%    0.242702  0.201734  0.393205  0.671497
50%    0.544619  0.471826  0.465014  0.787821
75%    0.546284  0.828424  0.628677  0.900605
max    0.724085  0.948514  0.670562  0.985563

In [104]:
newdf.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [105]:
newdf.index

Index([45, 46, 47, 48, 49], dtype='int64')

In [106]:
newdf.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [107]:
newdf.to_numpy()

array([[0.06603782, 0.47182618, 0.39320494, 0.67149734],
       [0.24270153, 0.94851409, 0.36331228, 0.39915258],
       [0.54628429, 0.20173357, 0.62867652, 0.78782061],
       [0.54461913, 0.82842421, 0.46501364, 0.98556252],
       [0.72408479, 0.17829265, 0.67056177, 0.90060452]])

In [108]:
newdf.T

         45        46        47        48        49
A  0.066038  0.242702  0.546284  0.544619  0.724085
B  0.471826  0.948514  0.201734  0.828424  0.178293
C  0.393205  0.363312  0.628677  0.465014  0.670562
D  0.671497  0.399153  0.787821  0.985563  0.900605

In [109]:
newdf.sort_index(axis=0,ascending=False)

           A         B         C         D
49  0.724085  0.178293  0.670562  0.900605
48  0.544619  0.828424  0.465014  0.985563
47  0.546284  0.201734  0.628677  0.787821
46  0.242702  0.948514  0.363312  0.399153
45  0.066038  0.471826  0.393205  0.671497

In [110]:
newdf.head()

           A         B         C         D
45  0.066038  0.471826  0.393205  0.671497
46  0.242702  0.948514  0.363312  0.399153
47  0.546284  0.201734  0.628677  0.787821
48  0.544619  0.828424  0.465014  0.985563
49  0.724085  0.178293  0.670562  0.900605

In [111]:
newdf.sum(axis=0)

A    2.123728
B    2.628791
C    2.520769
D    3.744638
dtype: float64

In [112]:
newdf["A"]>0.5

45    False
46    False
47     True
48     True
49     True
Name: A, dtype: bool

In [113]:
newdf[newdf["A"]>0.5]

           A         B         C         D
47  0.546284  0.201734  0.628677  0.787821
48  0.544619  0.828424  0.465014  0.985563
49  0.724085  0.178293  0.670562  0.900605

In [114]:
nextnewdf2 =newdf

In [115]:
newdf.copy(deep =True)

           A         B         C         D
45  0.066038  0.471826  0.393205  0.671497
46  0.242702  0.948514  0.363312  0.399153
47  0.546284  0.201734  0.628677  0.787821
48  0.544619  0.828424  0.465014  0.985563
49  0.724085  0.178293  0.670562  0.900605

In [116]:
df

          name  marks       city
first    harry     92      delhi
second   rohan     34     mumbai
third   skillf     24    chennai
fourth   shubh     37  bangalore
fifth    mohan     85  hyderabad

In [117]:
df.index =["0","1","2","3","4"]

In [118]:
df

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad