In [54]:
import numpy as np
import pandas as pd

In [55]:
dict1 = {
    "name": ["harry","rohan","skillf","shubh","mohan"],
    "marks":[92 ,34 ,24 ,37, 85],
    "city":["delhi","mumbai","chennai","bangalore","hyderabad"]                  }

In [56]:
df = pd.DataFrame(dict1)

In [57]:
df

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [58]:
df.to_csv("youtube.csv")

In [59]:
df.to_csv("youtube_no_index.csv", index=False)

In [60]:
df

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [61]:
df.head(2)

    name  marks    city
0  harry     92   delhi
1  rohan     34  mumbai

In [62]:
df.tail(2)

    name  marks       city
3  shubh     37  bangalore
4  mohan     85  hyderabad

In [63]:
df.describe()

           marks
count   5.000000
mean   54.400000
std    31.595886
min    24.000000
25%    34.000000
50%    37.000000
75%    85.000000
max    92.000000

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   marks   5 non-null      int64
 2   city    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [65]:
df= pd.read_csv("youtube_no_index.csv")

In [66]:
df["city"]

0        delhi
1       mumbai
2      chennai
3    bangalore
4    hyderabad
Name: city, dtype: str

In [67]:
df[["name","city"]]

     name       city
0   harry      delhi
1   rohan     mumbai
2  skillf    chennai
3   shubh  bangalore
4   mohan  hyderabad

In [68]:
df["name"][0] ="sonu"

C:\Users\JON\AppData\Local\Temp\ipykernel_15328\3738989102.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["name"][0] ="sonu"

In [69]:
df.index = ["first","second","third","fourth","fifth"]

In [70]:
pd.Series([1,2,3,4,5], index=["a","b","c","d","e"])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [71]:
pd.DataFrame(dict1)

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [72]:
newdf = pd.DataFrame(np.random.rand(350,4),index =np.arange(350),columns =["A","B","C","D"])

In [73]:
newdf

            A         B         C         D
0    0.360276  0.865017  0.640508  0.526299
1    0.394745  0.185120  0.390114  0.971172
2    0.335876  0.001789  0.447586  0.565787
3    0.015866  0.190620  0.249130  0.636547
4    0.159238  0.084376  0.503507  0.414418
..        ...       ...       ...       ...
345  0.699014  0.303569  0.679270  0.187244
346  0.817006  0.809851  0.204597  0.216239
347  0.697170  0.448266  0.482605  0.495917
348  0.243338  0.133476  0.424767  0.311492
349  0.838313  0.801748  0.344950  0.158163

[350 rows x 4 columns]

In [74]:
newdf = pd.DataFrame(np.random.rand(350,4),index =np.arange(350),columns =["A","B","C","D"]).head()
newdf

          A         B         C         D
0  0.177157  0.806907  0.924602  0.400191
1  0.078726  0.159380  0.110151  0.018754
2  0.247808  0.137639  0.352010  0.252996
3  0.459588  0.998120  0.145288  0.235452
4  0.289674  0.359898  0.123884  0.398810

In [75]:
newdf = pd.DataFrame(np.random.rand(50,4),index =np.arange(50),columns =["A","B","C","D"]).tail()
newdf.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.462379  0.724253  0.489971  0.493922
std    0.267842  0.239121  0.333691  0.096852
min    0.086362  0.459026  0.058037  0.354081
25%    0.365741  0.501887  0.422813  0.469169
50%    0.454346  0.747810  0.426620  0.477759
75%    0.601153  0.937527  0.556554  0.564868
max    0.804294  0.975017  0.985830  0.603735

In [76]:
newdf.tail()

           A         B         C         D
45  0.454346  0.459026  0.556554  0.354081
46  0.086362  0.937527  0.985830  0.469169
47  0.601153  0.975017  0.426620  0.603735
48  0.804294  0.501887  0.422813  0.477759
49  0.365741  0.747810  0.058037  0.564868

In [77]:
newdf.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.462379  0.724253  0.489971  0.493922
std    0.267842  0.239121  0.333691  0.096852
min    0.086362  0.459026  0.058037  0.354081
25%    0.365741  0.501887  0.422813  0.469169
50%    0.454346  0.747810  0.426620  0.477759
75%    0.601153  0.937527  0.556554  0.564868
max    0.804294  0.975017  0.985830  0.603735

In [78]:
newdf.dtypes

A    float64
B    float64
C    float64
D    float64
dtype: object

In [79]:
newdf.index

Index([45, 46, 47, 48, 49], dtype='int64')

In [80]:
newdf.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [81]:
newdf.to_numpy()

array([[0.45434613, 0.45902642, 0.55655431, 0.35408138],
       [0.08636154, 0.93752674, 0.98583   , 0.46916906],
       [0.60115281, 0.97501677, 0.42662024, 0.60373504],
       [0.80429376, 0.50188712, 0.42281288, 0.47775879],
       [0.36574089, 0.74780998, 0.0580371 , 0.56486756]])

In [82]:
newdf.T

         45        46        47        48        49
A  0.454346  0.086362  0.601153  0.804294  0.365741
B  0.459026  0.937527  0.975017  0.501887  0.747810
C  0.556554  0.985830  0.426620  0.422813  0.058037
D  0.354081  0.469169  0.603735  0.477759  0.564868

In [83]:
newdf.sort_index(axis=0,ascending=False)

           A         B         C         D
49  0.365741  0.747810  0.058037  0.564868
48  0.804294  0.501887  0.422813  0.477759
47  0.601153  0.975017  0.426620  0.603735
46  0.086362  0.937527  0.985830  0.469169
45  0.454346  0.459026  0.556554  0.354081

In [84]:
newdf.head()

           A         B         C         D
45  0.454346  0.459026  0.556554  0.354081
46  0.086362  0.937527  0.985830  0.469169
47  0.601153  0.975017  0.426620  0.603735
48  0.804294  0.501887  0.422813  0.477759
49  0.365741  0.747810  0.058037  0.564868

In [89]:
newdf.sum(axis=0)

A    2.311895
B    3.621267
C    2.449855
D    2.469612
dtype: float64

In [92]:
newdf["A"]>0.5

45    False
46    False
47     True
48     True
49    False
Name: A, dtype: bool

In [93]:
newdf[newdf["A"]>0.5]

           A         B         C         D
47  0.601153  0.975017  0.426620  0.603735
48  0.804294  0.501887  0.422813  0.477759