In [3]:
import numpy as np
import pandas as pd

In [4]:
dict1 = {
    "name": ["harry","rohan","skillf","shubh","mohan"],
    "marks":[92 ,34 ,24 ,37, 85],
    "city":["delhi","mumbai","chennai","bangalore","hyderabad"]                  }

In [5]:
df = pd.DataFrame(dict1)

In [6]:
df

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [7]:
df.to_csv("youtube.csv")

In [8]:
df.to_csv("youtube_no_index.csv", index=False)

In [9]:
df

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [10]:
df.head(2)

    name  marks    city
0  harry     92   delhi
1  rohan     34  mumbai

In [11]:
df.tail(2)

    name  marks       city
3  shubh     37  bangalore
4  mohan     85  hyderabad

In [12]:
df.describe()

           marks
count   5.000000
mean   54.400000
std    31.595886
min    24.000000
25%    34.000000
50%    37.000000
75%    85.000000
max    92.000000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      str
 1   marks   5 non-null      int64
 2   city    5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [14]:
df= pd.read_csv("youtube_no_index.csv")

In [15]:
df["city"]

0        delhi
1       mumbai
2      chennai
3    bangalore
4    hyderabad
Name: city, dtype: str

In [16]:
df[["name","city"]]

     name       city
0   harry      delhi
1   rohan     mumbai
2  skillf    chennai
3   shubh  bangalore
4   mohan  hyderabad

In [17]:
df["name"][0] ="sonu"

C:\Users\JON\AppData\Local\Temp\ipykernel_15328\3738989102.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["name"][0] ="sonu"

In [18]:
df.index = ["first","second","third","fourth","fifth"]

In [19]:
pd.Series([1,2,3,4,5], index=["a","b","c","d","e"])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [20]:
pd.DataFrame(dict1)

     name  marks       city
0   harry     92      delhi
1   rohan     34     mumbai
2  skillf     24    chennai
3   shubh     37  bangalore
4   mohan     85  hyderabad

In [21]:
newdf = pd.DataFrame(np.random.rand(350,4),index =np.arange(350),columns =["A","B","C","D"])

In [22]:
newdf

            A         B         C         D
0    0.595969  0.127819  0.447645  0.025718
1    0.818101  0.207501  0.690769  0.153200
2    0.854007  0.437749  0.856225  0.043103
3    0.899649  0.248672  0.105045  0.897710
4    0.923128  0.354754  0.306704  0.077297
..        ...       ...       ...       ...
345  0.846160  0.624047  0.494711  0.494050
346  0.999200  0.611050  0.280120  0.825547
347  0.041134  0.695361  0.003580  0.422297
348  0.462215  0.146828  0.464443  0.606007
349  0.002113  0.231250  0.561889  0.421283

[350 rows x 4 columns]

In [23]:
newdf = pd.DataFrame(np.random.rand(350,4),index =np.arange(350),columns =["A","B","C","D"]).head()
newdf

          A         B         C         D
0  0.348697  0.153280  0.294540  0.455028
1  0.315443  0.248354  0.806410  0.748319
2  0.453574  0.739233  0.230209  0.463768
3  0.046357  0.195098  0.859001  0.794371
4  0.169718  0.271110  0.363937  0.066425

In [32]:
newdf = pd.DataFrame(np.random.rand(50,4),index =np.arange(50),columns =["A","B","C","D"]).tail()
newdf.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.483675  0.693232  0.542490  0.482903
std    0.344050  0.136501  0.282700  0.422809
min    0.007044  0.461934  0.106881  0.014217
25%    0.290278  0.692150  0.504930  0.244248
50%    0.508479  0.743414  0.512680  0.296244
75%    0.798215  0.753400  0.770213  0.885234
max    0.814360  0.815262  0.817746  0.974570

In [25]:
newdf.tail()

            A         B         C         D
345  0.519680  0.321210  0.665894  0.325047
346  0.033394  0.918964  0.213104  0.039526
347  0.359239  0.088511  0.882631  0.192861
348  0.716249  0.636115  0.434438  0.719804
349  0.094676  0.108624  0.589318  0.235453

In [26]:
newdf.describe()

              A         B         C         D
count  5.000000  5.000000  5.000000  5.000000
mean   0.344648  0.414685  0.557077  0.302538
std    0.286488  0.357816  0.251109  0.255109
min    0.033394  0.088511  0.213104  0.039526
25%    0.094676  0.108624  0.434438  0.192861
50%    0.359239  0.321210  0.589318  0.235453
75%    0.519680  0.636115  0.665894  0.325047
max    0.716249  0.918964  0.882631  0.719804

In [ ]:
newdf.iloc[0, 0] = "sonu"

KeyError: 1